site_name: CM-Well
repo_url: https://github.com/CM-Well/CM-Well
#site_url: https://example.com/foo333/
site_description: CM-Well Documentation
site_author: CM-Well contibutors
#remote_branch
#remote_name
copyright: CM-Well copyright
#You want to set it to true after the documentation will stabilize (fails on warnings)
#strict: true
#It's needed in order to create proper html links instead of directories. Only this way CM-Well can properly handle the links.
use_directory_urls: false
theme: 
  name: 'material'
  #logo: 'images/logo.svg' logo can be either image or icon!
  #favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true - Do we want tabs?
  #font: false - to be complaint with GDPR (but will change the fonts. use custom template for the fonts section for that)
extra:
  social:
    - type: 'github'
      link: 'https://github.com/CM-Well/CM-Well'
#    - type: 'gitter'
#      link: 'https://gitter.im/CM-Well/CM-Well' - I couldn't get the gitter icon to be inversed colors
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true  
nav:
  - Home:
    - qq: index.md
    - Bug Tracker: https://github.com/CM-Well/CM-Well/issues
    - ReleaseNotes:
      - ReleaseNotes/ReleaseNotes.Amoeba.Feb.2017.md
      - ReleaseNotes/ReleaseNotes.Beowulf.Feb.2017.md
      - ReleaseNotes/ReleaseNotes.CElegans.Mar.2017.md
      - ReleaseNotes/ReleaseNotes.Dec.15.2016.md
      - ReleaseNotes/ReleaseNotes.Dec.7.2016.md
      - ReleaseNotes/ReleaseNotes.Dolphin.Mar.2017.md
      - ReleaseNotes/ReleaseNotes.Firebird.May.2017.md
      - ReleaseNotes/ReleaseNotes.Gopher.May.2017.md
      - ReleaseNotes/ReleaseNotes.Hydra.June.2017.md
      - ReleaseNotes/ReleaseNotes.Iguana.July.2017.md
      - ReleaseNotes/ReleaseNotes.Jaguar.August.2017.md
      - ReleaseNotes/ReleaseNotes.Jan.17.2017.md
      - ReleaseNotes/ReleaseNotes.Jan.4.2017.md
      - ReleaseNotes/ReleaseNotes.Kingbird.September.2017.md
      - ReleaseNotes/ReleaseNotes.Lynx.September.2017.md
      - ReleaseNotes/ReleaseNotes.Mono.November.2017.md
      - ReleaseNotes/ReleaseNotes.Nautilus.November.2017.md
      - ReleaseNotes/ReleaseNotes.Nov.10.2016.md
      - ReleaseNotes/ReleaseNotes.Oct.6.2016.md
      - ReleaseNotes/ReleaseNotes.Octopus.December.2017.md
      - ReleaseNotes/ReleaseNotes.Piranha.January.2018.md
      - ReleaseNotes/ReleaseNotes.Quetzal.February.2018.md
      - ReleaseNotes/ReleaseNotes.Rhino.March.2018.md
      - ReleaseNotes/ReleaseNotes.Sept.11.2016.md
      - ReleaseNotes/ReleaseNotes.Swan.April.2018.md
      - ReleaseNotes/ReleaseNotes.TOC.md
      - ReleaseNotes/ReleaseNotes.Turtle.May.2018.md
      - ReleaseNotes/ReleaseNotes.Unicorn.June.2018.md
      - ReleaseNotes/ReleaseNotes.Viper.June.2018.md
      - ReleaseNotes/ReleaseNotes.Wombat.August.2018.md
      - ReleaseNotes/ReleaseNotes.Xerus.October.2018.md
      - ReleaseNotes/ReleaseNotes.Yak.November.2018.md
      - ReleaseNotes/ReleaseNotes.Zebra.December.2018.md
  - Developer Guide:
    - DeveloperGuide/DevGuide.AdvancedQueries.md
    - DeveloperGuide/DevGuide.BasicQueries.md
    - DeveloperGuide/DevGuide.BestPractices.ConditionalUpdates.md
    - DeveloperGuide/DevGuide.BestPractices.DeletingKnownFieldValues.md
    - DeveloperGuide/DevGuide.BestPractices.ManagingRetries.md
    - DeveloperGuide/DevGuide.BestPractices.StreamingMethods.md
    - DeveloperGuide/DevGuide.BestPractices.TOC.md
    - DeveloperGuide/DevGuide.CallingJavaScalaFunctionsFromSPARQLQueries.md
    - DeveloperGuide/DevGuide.CM-WellSecurityFeatures.md
    - DeveloperGuide/DevGuide.CurlUtility.md
    - DeveloperGuide/DevGuide.DosAndDonts.md
    - DeveloperGuide/DevGuide.ManagingUsers.md
    - DeveloperGuide/DevGuide.StreamingDataFromCM-Well.md
    - DeveloperGuide/DevGuide.SubscribingToReal-TimeUpdates.md
    - DeveloperGuide/DevGuide.TOC.md
    - DeveloperGuide/DevGuide.UpdatingCM-Well.md
    - DeveloperGuide/DevGuide.UsingElasticSearchStatistics.md
    - DeveloperGuide/DevGuide.UsingSPARQLOnCM-WellInfotons.md
    - DeveloperGuide/DevGuide.WorkingWithNamedSub-Graphs.md  
    - API reference:
      - DeveloperGuide/API/API/API.TOC.md      
      - DeveloperGuide/API/API.FieldConditionSyntax
      - DeveloperGuide/API/API.FieldNameFormats.md
      - DeveloperGuide/API/API.FromAndToDatetimeFormatting.md
      - DeveloperGuide/API/API.InputAndOutputFormats.md
      - DeveloperGuide/API/API.Login.Login.md
      - DeveloperGuide/API/API.PagingThroughResultsWithOffsetAndLengthParameters.md
      - DeveloperGuide/API/API.QueryParameters.md
      - DeveloperGuide/API/API.ReturnCodes.md
      - DeveloperGuide/API/API.SortingResultsWithTheSort-byFlag.md
      - DeveloperGuide/API/API.TOC.md
      - DeveloperGuide/API/API.UsingTheBlockingFlag.md
      - DeveloperGuide/API/API.UsingTheRecursiveFlag.md
      - DeveloperGuide/API/API.UsingTheWith-dataFlag.md
      - DeveloperGuide/API/API.UsingTheWith-deletedFlag.md
      - DeveloperGuide/API/API.UsingTheWith-historyFlag.md
      - DeveloperGuide/API/Intro.OverviewOfTheCM-WellAPI.md
      - DeveloperGuide/API/API.MetadataFields.md
      - DeveloperGuide/API/API.ProtocolSystemField.md
      - DeveloperGuide/API/API.UsingConditionalUpdates.md
      - Update:
        - DeveloperGuide/API/Update/API.Update.AddFileInfoton.md
        - DeveloperGuide/API/Update/API.Update.AddInfotonsAndFieldsToSubGraph.md
        - DeveloperGuide/API/Update/API.Update.AddLinkInfoton.md
        - DeveloperGuide/API/Update/API.Update.DeleteASingleInfoton.md
        - DeveloperGuide/API/Update/API.Update.DeleteFields.md
        - DeveloperGuide/API/Update/API.Update.DeleteMultipleInfotons.md
        - DeveloperGuide/API/Update/API.Update.DeleteOrReplaceValuesInNamedSubGraph.md
        - DeveloperGuide/API/Update/API.Update.DeleteSpecificFieldValues.md
        - DeveloperGuide/API/Update/API.Update.Purge.md
        - DeveloperGuide/API/Update/API.Update.ReplaceFieldValues.md
        - DeveloperGuide/API/Update/API.Update.TrackUpdates.md
        - DeveloperGuide/API/Update/API.Update.AddInfotonsAndFields.md
      - Get:
        - DeveloperGuide/API/Get/API.Get.GetMultipleInfotonsByURI.md
        - DeveloperGuide/API/Get/API.Get.GetSingleInfotonByURI.md
        - DeveloperGuide/API/Get/API.Get.GetSingleInfotonByUUID.md
      - Stream:
        - DeveloperGuide/API/Stream/API.Stream.ConsumeNextBulk.md
        - DeveloperGuide/API/Stream/API.Stream.ConsumeNextChunk.md
        - DeveloperGuide/API/Stream/API.Stream.CreateConsumer.md
        - DeveloperGuide/API/Stream/API.Stream.CreateIterator.md
        - DeveloperGuide/API/Stream/API.Stream.StreamInfotons.md
        - DeveloperGuide/API/Stream/API.Stream.GetNextChunk.md
      - Traversal:
        - DeveloperGuide/API/Traversal/API.Traversal.Intro.md
        - DeveloperGuide/API/Traversal/API.Traversal.Operands.md
        - DeveloperGuide/API/Traversal/API.Traversal.TOC.md
        - DeveloperGuide/API/Traversal/API.Traversal.gqp.md
        - DeveloperGuide/API/Traversal/API.Traversal.xg.md
        - DeveloperGuide/API/Traversal/API.Traversal.yg.md
      - Query:
        - DeveloperGuide/API/Query/API.Query.ApplyGremlinToQueryResults.md
        - DeveloperGuide/API/Query/API.Query.ApplySPARQLToEntireGraph.md
        - DeveloperGuide/API/Query/API.Query.ApplySPARQLToQueryResults.md
        - DeveloperGuide/API/Query/API.Query.DataStatistics.md
        - DeveloperGuide/API/Query/API.Query.QueryForInfotonsUsingFieldConditions.md
        - DeveloperGuide/API/Query/API.Query.QueryForQuadsByTheirLabel.md
      - Authorization:
        - DeveloperGuide/API/Authorization/API.Auth.ChangePassword.md
        - DeveloperGuide/API/Authorization/API.Auth.GeneratePassword.md
        - DeveloperGuide/API/Authorization/API.Auth.InvalidateCache.md
      - Subscribe:
        - DeveloperGuide/API/Subscribe/API.Subscribe.PullNewData.md
        - DeveloperGuide/API/Subscribe/API.Subscribe.SubscribeForPulledData.md
        - DeveloperGuide/API/Subscribe/API.Subscribe.SubscribeForPushedData.md
        - DeveloperGuide/API/Subscribe/API.Subscribe.Unsubscribe.md
  - Tutorial:
    - Tutorial/Tutorial.Building.md
    - Tutorial/Tutorial.Docker.md
    - Tutorial/Tutorial.HandsOnExercises.AddFileInfoton.md
    - Tutorial/Tutorial.HandsOnExercises.AddInfotonsAndFields.md
    - Tutorial/Tutorial.HandsOnExercises.DeleteInfotonsAndFields.md
    - Tutorial/Tutorial.HandsOnExercises.GetInfotonsByURI.md
    - Tutorial/Tutorial.HandsOnExercises.QueryForInfotons.md
    - Tutorial/Tutorial.HandsOnExercises.QueryWithGremlin.md
    - Tutorial/Tutorial.HandsOnExercises.QueryWithSPARQL.md
    - Tutorial/Tutorial.HandsOnExercises.StreamWithIterator.md
    - Tutorial/Tutorial.HandsOnExercises.StreamWithTheStreamOperation.md
    - Tutorial/Tutorial.HandsOnExercises.SubscribeForPulledData.md
    - Tutorial/Tutorial.HandsOnExercisesTOC.md
    - Tutorial/Tutorial.HandsOnExercises.UpdateFields.md
    - Tutorial/Tutorial.HandsOnExercises.WorkWithSubGraphs.md
    - Tutorial/Tutorial.TOC.md
  - Tools:
    - Tools/Tools.TOC.md
    - Tools/Tools.UsingCM-WellDocker.md
    - Tools/Tools.UsingTheCM-WellDownloader.md
    - Tools/Tools.UsingTheCM-WellIngester.md
    - Tools/Tools.UsingTheCM-WellSparkConnector.md
    - Tools/Tools.UsingTheSPARQLTriggerProcessor.md
